#!/bin/bash

###################################################################
#Script Name    : git-branch-name
#Description    : Returns git branch infromation for a specific path
#Author         : Rohan Yadav
#Email          : yrohan31@gmail.com
###################################################################

dir="$1"
[ -d $dir ] || exit 1

# Changing to the directory
cd "$dir" > /dev/null

gitstatus=$( LC_ALL=C git status --untracked-files=all --porcelain --branch 2>&1 )

# if the status is fatal, exit now
[ $? -ne 0 ] && exit 0

while IFS='' read -r line || [[ -n "$line" ]]; do
  status=${line:0:2}
  case "$status" in
    '##')
      if [[ $line = *"No commits yet"* ]]; then
        # fixes #54 (garbage output on new repos)
        line=$(echo $line | sed  "s/.*yet on //")
      fi
      branch_line="${line/\.\.\./^}" ;;
  esac
done <<< "$gitstatus"

IFS="^" read -ra branch_fields <<< "${branch_line/\#\# }"
branch="${branch_fields[0]}"
echo $branch
